"""empty message

Revision ID: 14814a653e36
Revises: 3bffee62cefd
Create Date: 2020-08-18 07:36:23.479196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14814a653e36'
down_revision = '3bffee62cefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors_movies',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    op.alter_column('movies', 'about',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'about',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('actors_movies')
    # ### end Alembic commands ###
