"""empty message

Revision ID: 3bffee62cefd
Revises: cab577831fc8
Create Date: 2020-08-18 06:59:01.341796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bffee62cefd'
down_revision = 'cab577831fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('about', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'about')
    # ### end Alembic commands ###
